import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import Timeline from "@mui/lab/Timeline";
import TimelineItem from "@mui/lab/TimelineItem";
import TimelineSeparator from "@mui/lab/TimelineSeparator";
import TimelineConnector from "@mui/lab/TimelineConnector";
import TimelineContent from "@mui/lab/TimelineContent";
import TimelineDot from "@mui/lab/TimelineDot";
import "../App.css";
import "../style/about.css";

function AboutMe() {
  const [currY, setCurrY] = useState(0);
  const [prev, setPrev] = useState(0);
  const [outlined, setOutline] = useState([true, false, false, false]);

  const navigate = useNavigate();

  window.addEventListener("scroll", () => {
    setPrev(currY);
    setCurrY(window.scrollY);
  });

  function handleDotOne() {
    setOutline([true, false, false, false]);
  }
  function handleDotTwo() {
    setOutline([false, true, false, false]);
  }
  function handleDotThree() {
    setOutline([false, false, true, false]);
  }
  function handleDotFour() {
    setOutline([false, false, false, true]);
  }
  const toggleHide = currY > prev ? "hide" : "return-btn";

  const timelineContainerStyle = {};

  console.log(window.location.href.innerWidth)

  

  return (
    <div className="abt">
      <div style={timelineContainerStyle} className="timeLineContainer">
        <Timeline className="timeLine" align="left" position="left">
          <TimelineItem>
            <TimelineSeparator>
              <a href="#my_story">
                <TimelineDot
                  variant={outlined[0] ? "filled" : "outlined"}
                  className="separator"
                  onClick={handleDotOne}
                />
              </a>
              <TimelineConnector className="connector" />
            </TimelineSeparator>
            <TimelineContent>My Story</TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineSeparator>
              <a href="#experience">
                <TimelineDot
                  variant={outlined[1] ? "filled" : "outlined"}
                  className="separator"
                  onClick={handleDotTwo}
                />
              </a>
              <TimelineConnector className="connector" />
            </TimelineSeparator>
            <TimelineContent>Experience</TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineSeparator>
              <a href="#education">
                <TimelineDot
                  variant={outlined[2] ? "filled" : "outlined"}
                  className="separator"
                  onClick={handleDotThree}
                />
              </a>
              <TimelineConnector className="connector" />
            </TimelineSeparator>
            <TimelineContent>Education</TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineSeparator>
              <a href="#interest">
                <TimelineDot
                  variant={outlined[3] ? "filled" : "outlined"}
                  className="separator"
                  onClick={handleDotFour}
                />
              </a>
            </TimelineSeparator>
            <TimelineContent>Interest</TimelineContent>
          </TimelineItem>
        </Timeline>
      </div>
      <button
        className={toggleHide}
        onClick={() => navigate("/")}
        disabled={currY > prev ? true : false}
      >
        Back Home
      </button>

      <div id="me1" className="me">
        <h1 id="my_story">My Story</h1>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
      </div>
      <div className="me">
        <h1 id="experience">Experience</h1>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST TEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
      </div>
      <div id="education" className="me">
        <h1>Education</h1>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST TEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
      </div>
      <div id="interest" className="me">
        <h1>Interest</h1>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST TEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
        <p>
          TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTEST TEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTESTTEST
          TESTTESTTESTTEST TESTTESTTESTTEST TESTTESTTEST
        </p>
      </div>
    </div>
  );
}

export default AboutMe;
