const projects = [
    {
      name: "Get Away",
      description: "TEST TESTTESTTESTTESTTEST TEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTEST",
      video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      image:"../projectImages/GetAway.png",
    },
    {
        name: "Cloud Watch",
        description: "TEST TESTTESTTESTTESTTEST TEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTEST",
        video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image:"../projectImages/CloudWatch.png",
      },
      {
        name: "Planters",
        description: "TEST TESTTESTTESTTESTTEST TEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTESTTEST TESTTESTTESTTESTTEST",
        video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image:"../projectImages/Planters.png",
      },
  ];

  export default projects;